### ISSUE TITLE
运行cli.py出错

### ISSUE THREAD

**Issue by linxi0428** [ysrc/GourdScanV2#15]
前几天耽搁了下，一直说试用下2.1都没有时间，今天周末赶紧爬起来试试
遇到几个错误，看前面的issue解决了一些，但是还遇到这个错误，求教！
![image](https://cloud.githubusercontent.com/assets/24444173/23818887/a1423c7a-063a-11e7-8825-abd68f3bb0bf.png)

**Comment by linxi0428** [comment]
我在kali下能够安装成功，这一块可能是用户权限的问题，最好在root下，可以避免很多问题，sudo安装什么的并不能解决问题

**Comment by linxi0428** [comment]
session.py中第一次打开session的时候，后面漏掉了‘r’，会报错

def check(session):
    with **open(os.getcwd() + os.path.sep + "session",'r')** as f:
        lines = f.readlines()
        f.close()
        for line in lines:
            if session == line.strip():
                return True
        return False

**Comment by linxi0428** [comment]
root@kali-ch:/usr/bin# redis-server /root/GourdScanV2/redis.conf

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 330
>>> 'repl-diskless-sync no'
Bad directive or wrong number of arguments

启动redis-server的时候报了这个错误

**Comment by ihacku** [comment]
之前合并了一个改动比较大的外部pr，是有点问题的，手头有点事情没跟进去测，等下周整一下。

**Comment by linxi0428** [comment]
嗯嗯，辛苦！大家对这一块还是比较感兴趣的！我也可以趁机研究研究
刚刚上面说的那个redis报错是因为版本的问题，我把kali中的2.8版本的redis卸载，然后安装了最新的3.2的就没问题了！

**Comment by ihacku** [comment]
ok 回头文档里我加一下redis版本的注意。

**Comment by linxi0428** [comment]
redis数据库运行时，感觉没有读取我们自己的配置，虽然我都替换成你设置的那个redis.conf文件了
一直提示数据库未配置密码，这个问题在手工添加redis数据库的密码时得到解决
redis-cli
config set requirepass Y3rc_Alw4ys_B3_W1th_Y0u

**Comment by linxi0428** [comment]
session.py文件中
from hashlib import md5
建议直接改成
import md5
不然认证过程一直通不过，报500错误

**Comment by linxi0428** [comment]
终于进来了，第一感觉就是UI比2.0漂亮多了，很不错！
![image](https://cloud.githubusercontent.com/assets/24444173/23821531/0ede0892-0670-11e7-90d4-c3dca7b873d9.png)

**Comment by rangeme** [comment]
之前补考，没时间搞，现在各种bug正在跟进，
