### ISSUE TITLE
使用后的一些问题

### ISSUE THREAD

**Issue by ff00x0** [ysrc/GourdScanV2#2]
ssh密码敲了几遍都不对，修改root密码才进入，请核实一下；
使用中很卡，不知道是不是我在虚拟机里用docker的原因；
扫描结果页面的定时刷新感觉可以去掉，影响看扫描结果，自己手动刷新就行了；
感谢同程的开源，功能很强大

**Comment by rangeme** [comment]
密码是正确的，我自己也输错了，后来输正确了就进去了
![qq 20161021161533](https://cloud.githubusercontent.com/assets/10612232/19591418/8c096874-97a9-11e6-9ca3-72303960156c.png)

**Comment by rangeme** [comment]
定时刷新那里的问题，以后会去掉或者设置为10分钟一次
