### ISSUE TITLE
..想push也没权限。。醉了

### ISSUE THREAD

**Issue by iusky** [ysrc/GourdScanV2#21]
root@docker:~/GourdScanV2# git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Username for 'https://github.com': iusky
Password for 'https://iusky@github.com': 
remote: Permission to ysrc/GourdScanV2.git denied to iusky.
fatal: unable to access 'https://github.com/ysrc/GourdScanV2.git/': The requested URL returned error: 403

写了一个linux的安装详细步骤
跳过那些安装系统，设置ip的部分

# 1、安装基础环境

## 安装系统环境

`apt-get insatll python-pip python-dev python-libpcap libpcap-dev libdnet redis-server`

## 安装sqlmap（可选）

`git clone https://github.com/sqlmapproject/sqlmap.git`

## 下载GourdScanV2 源码进行安装

`git clone https://github.com/ysrc/GourdScanV2.git`

`pip install -r requirements.txt`

`python setup.py install`

# 2、配置redis

`redis-cli`

`config set requirepass Y3rc_Alw4ys_B3_W1th_Y0u`

`exit`

# 创建软连接到GourdScanV2安装目录

ps:先到/usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/该目录看看是否存在该目录，如果存在就进行下一步，不存在则找到python第三方库的安装目录后在进行操作

`cd /usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg/`

`ln -s /sky/GourdScanV2/gourdscan`

tips:上面的sky代表的是你下载GourdScanV2的起始路径，不可直接抄写执行

# 3、运行

这时候基本已经完成了98%  
先跑一下，按照我的步骤来应该是不会报错的

`python /sky/GourdScanV2/gourdscan/cli.py`

tips:上面的sky代表的是你下载GourdScanV2的起始路径，不可直接抄写执行

然后打开浏览器访问ip:8000就可以得到下图这样的界面  
![file](http://static.secquan.org/14828a13876515eb1226998288898753.png-quanzi)

然后输入账号密码进入系统

```php 
admin
Y3rc_admin
```
# 4、根据自己的需求进行系统配置，点击config

![file](http://static.secquan.org/2b242f59adf0eff0da4539af86068d47.png-quanzi)

# 5、根据自己的需求进行扫描配置，点击scan config

![file](http://static.secquan.org/1675498eba2eb1aa5f01c2e53677acfa.png-quanzi)

# 7、根据自己的需求进行代理配置，点击start monitor

tips:将ip改为你虚拟机的ip地址

![file](http://static.secquan.org/cdcc0e2ca9b71b6853acbf91a8db9ddc.png-quanzi)

![file](http://static.secquan.org/459bc98f781f1537ca9c713e0943937f.png-quanzi)

# 6、然后设置浏览器代理为你的ip，端口为10086，即可成功运行

如下图

![file](http://static.secquan.org/6c00aec0b3df271017309ecbacef6434.png-quanzi)

![file](http://static.secquan.org/d10c01c3bc2a102fe78e4059689999f5.png-quanzi)

![file](http://static.secquan.org/2afa80f9b315ab10b0f6bcd6f070d237.png-quanzi)

![file](http://static.secquan.org/d207b65c5c9df356e04562d574f3b11a.png-quanzi)

**Comment by iusky** [comment]
原文地址：https://www.secquan.org/Tools/150

**Comment by rangeme** [comment]
@iusky 大兄弟，感谢了，不过目前还别忙吧，还在测试中，要不等我们正式发布了再发使用方法？

**Comment by iusky** [comment]
我就是闲暇的时候随便写了一下，发到社区：P 233333代我向wolf问好 2333333
