### ISSUE TITLE
docker没起来（2.1版本）

### ISSUE THREAD

**Issue by guixiaomin** [ysrc/GourdScanV2#23]
1，运行cli.py的时候报模块错误。根据issues反馈的。加上sys.path走通了。

2，运行起来后随之而来的问题就是访问web控制端 500错误了
赶脚在基于ubuntu的docker，还是ubuntu系统。redis都没起来，连接本地6379报错。

快点修。。坐等更新。

**Comment by rangeme** [comment]
@guixiaomin 这个我已经更新了，你再pull一下看看，如果还有问题再回复下？

**Comment by guixiaomin** [comment]
那个。。。。docker build没起来。有错误
zip_safe flag not set; analyzing archive contents...
gourdscan.web.app: module references __file__
gourdscan.lib.settings: module references __file__
creating dist
creating 'dist/gourdscan-2.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing gourdscan-2.1-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg
Extracting gourdscan-2.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding gourdscan 2.1 to easy-install.pth file
Installing gourdscan script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/gourdscan-2.1-py2.7.egg
Processing dependencies for gourdscan==2.1
Searching for pylibpcap
Reading https://pypi.python.org/simple/pylibpcap/
No local packages or download links found for pylibpcap
error: Could not find suitable distribution for Requirement.parse('pylibpcap')
The command '/bin/sh -c cd /home/gourdscan && python setup.py install' returned a non-zero code: 1

**Comment by rangeme** [comment]
是的，我这本地有点问题，一直在测试。。。再等一下

**Comment by guixiaomin** [comment]
@rangeme 好的。坐等。本来docker就是图环境安装方便。

**Comment by xMario0** [comment]
我也这个问题  不知道解决了没

**Comment by rangeme** [comment]
@xMario0 @guixiaomin 现在试试docker？

**Comment by xMario0** [comment]
@rangeme 已经解决
