### ISSUE TITLE
docker redis 3.2.8 也报Bad directive or wrong number of arguments

### ISSUE THREAD

**Issue by cnwpdb** [ysrc/GourdScanV2#25]
1.进入docker后redis-server ~/gourdscan/redis.conf gourdscan  提示
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 1021
>>> '"gourdscan"'
Bad directive or wrong number of arguments

2.redis 默认是3.0  然后升级到最新3.2.8,但是还报同样的错误
![image](https://cloud.githubusercontent.com/assets/20767942/24825259/bdbd4cea-1c4d-11e7-907d-72139ff43671.png)

**Comment by rangeme** [comment]
我readme写错了，gourdscan那里没有换行，重新看看readme吧

**Comment by ning1022** [comment]
我这里也遇到了这个问题。
```
root@8300b63ef106:~# redis-server ~/gourdscan/conf/redis.conf gourdscan

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 92
>>> 'tcp-backlog 511'
Bad directive or wrong number of arguments
root@8300b63ef106:~# redis-server ~/gourdscan/conf/redis.conf

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 92
>>> 'tcp-backlog 511'
Bad directive or wrong number of arguments
```
怎么解决的呢？

**Comment by im23pds** [comment]
redis-server redis.conf

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 92
>>> 'tcp-backlog 511'
Bad directive or wrong number of arguments

root@ea580f31cbc:~/gourdscan/conf# ls -l
total 68
-rw-r--r-- 1 root root  1566 Nov  1  2017 conf.json
-rw-r--r-- 1 root root  1176 Nov  1  2017 key.crt
-rw-r--r-- 1 root root   887 Nov  1  2017 key.pem
-rw-r--r-- 1 root root 45392 Nov  1  2017 redis.conf
drwxr-xr-x 2 root root  4096 Nov  1  2017 rules
-rw-r--r-- 1 root root    99 Nov  1  2017 session

root@ea580f31cbc:~/gourdscan/conf# redis-server -v
Redis server v=2.8.4 sha=00000000:0 malloc=jemalloc-3.5.1 bits=64 build=645b61b5aa39f6b1
