### ISSUE TITLE
MAC 安装问题小总结

### ISSUE THREAD

**Issue by wstart** [ysrc/GourdScanV2#27]
requirement.txt  缺少  tornado   pcapy

报错为 
ImportError: No module named dumbnet
 需要装  libdnet  

git clone https://github.com/dugsong/libdnet.git
cd libdnet
./configure && make
cd python
python setup.py install

**Comment by neargle** [comment]
fixed e3233eb3aea866ca38ecaab70479fd95cab58f4e
