### ISSUE TITLE
invalid hash, u bad hacker

### ISSUE THREAD

**Issue by F1uYu4n** [ysrc/GourdScanV2#3]
命中细节中，详情查看处点进去显示invalid hash, u bad hacker

**Comment by rangeme** [comment]
你hash不存在还是被删了？刷新下试试

**Comment by Ge0metryAI** [comment]
我的也是这样,重启过程序很多次,都是一样.

**Comment by rangeme** [comment]
@jhhd88 @F1uYu4n 有更详细的细节么，最好可以深究下？方便我debug，我这没出现过这样的情况

**Comment by rip1s** [comment]
我的也是这个样子，点击详细就这样，默认配置，按照你的readme来的
