### ISSUE TITLE
redis加载该项目redis.conf时出现问题

### ISSUE THREAD

**Issue by Asteriska001** [ysrc/GourdScanV2#31]
![default](https://user-images.githubusercontent.com/15817126/29248786-f550c114-8052-11e7-87b5-19e4eee8a1df.PNG)
![2](https://user-images.githubusercontent.com/15817126/29248789-fea25516-8052-11e7-95d7-c86db0c81259.PNG)
![3](https://user-images.githubusercontent.com/15817126/29248790-0176cf9c-8053-11e7-9954-176e821558ec.PNG)

**Comment by ihacku** [comment]
请问你的redis版本是？

**Comment by Asteriska001** [comment]
Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

**Comment by ihacku** [comment]
先把所有redis进程杀掉，再指定 conf/redis.conf 启动试试。

**Comment by Asteriska001** [comment]
似乎没什么用
![1](https://user-images.githubusercontent.com/15817126/29256113-4f78f36e-80da-11e7-8cc0-0befd6189ec1.png)

**Comment by rangeme** [comment]
你可以把版本升到最新版试试
