### ISSUE TITLE
好几处bug？

### ISSUE THREAD

**Issue by R0Y4l** [ysrc/GourdScanV2#6]
我搭建了之后，本地设置10086为代理端口。
然后生产者好像生产很少。
比如我发生了100次请求。可是 all requests显示的才8条数据而已。
我可以保持每次的请求都不一样，我感觉是不是你那个url优化过度了？
而且不能查看是哪8条数据？查看不了详情？

**Comment by rangeme** [comment]
过滤了很多不需要检测的后缀名，要查看的话，可以进入redis查看，百度下redis的用法即可。

**Comment by R0Y4l** [comment]
昨晚稍微详细研究了下，是可以用了。不过这也太占内存了吧。。。。一运行，整个机子都热起来了。。
是本身就这样，还是代码还有待优化？还有，不能查看所有详细，还要去redis看，有点麻烦。
还要从docker进去，能不能顺便加个浏览全部的功能

**Comment by R0Y4l** [comment]
还有抓取不了post的数据

**Comment by rangeme** [comment]
占内存的问题应该是线程太多，gdscan_worker/selfscan最下面一行里，配置的是50个线程，你要是电脑太热可以改改，本来是看冬天了，送点福利。。。已经记录了，下个版本会把配置详细化。

**Comment by Wyc0** [comment]
支持然哥

**Comment by hackzx** [comment]
「_本来是看冬天了，送点福利_」看得我笑了出来。
