### ISSUE TITLE
HTTPS页面的问题

### ISSUE THREAD

**Issue by linxi0428** [ysrc/GourdScanV2#9]
这一块解决起来始终是个棘手的问题，建议在服务器设立vpn服务，客户端这边通过拨接vpn，流量一样是走的代理服务器，那么在服务器只要抓取vpn流量即可，由于是vpn服务器，所以这些流量都是明文的！

**Comment by linxi0428** [comment]
对了，啥时候再改进下啊，大神，大家都很期待呢！

**Comment by rangeme** [comment]
vpn也是一样的，主要的问题还是在https抓包上面，https本来就是为了防止中间人攻击才做出来的，按照道理来说，vpn只是做转发，无法监听到https包的详细内容，要想抓https包只能从浏览器插件和自制证书两个方向来整，浏览器插件正在准备中，做不做得出来还得看有没有接口。另外如果http抓包的话，只要流量不大，pcap和scapy本机就可以很轻松的抓网卡。
另外v2.1正在写，已经差不多了，放几张图看看先
![Markdown](http://i1.piimg.com/1949/65dbdcc5b59f24f4.jpg)
![Markdown](http://i1.piimg.com/1949/4068a711e503b12e.jpg)
![Markdown](http://i1.piimg.com/1949/76f78f659c5e9f62.jpg)

**Comment by rangeme** [comment]
![Markdown](http://i1.piimg.com/1949/4068a711e503b12e.jpg)

**Comment by linxi0428** [comment]
可以，更新了！马上尝试下！
